name: build-push

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: { }

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Собираем имя образа автоматически и приводим к lowercase: ghcr.io/<owner>/<repo>
      - name: Compute image name (lowercase)
        id: names
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          REPO="${GITHUB_REPOSITORY#*/}"
          REPO_LC="${REPO,,}"
          echo "IMAGE=ghcr.io/${OWNER_LC}/${REPO_LC}" >> $GITHUB_ENV
          echo "image=${OWNER_LC}/${REPO_LC}" >> $GITHUB_OUTPUT
          echo "Image will be: ghcr.io/${OWNER_LC}/${REPO_LC}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ startsWith(github.ref, 'refs/heads/master') && 'master' || 'main' }}
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max